# Generated by Django 5.1.1 on 2024-09-21 12:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="content",
            new_name="text",
        ),
    ]
